baseURL: 'http://trumankautzman.com/'
languageCode: 'en-us'
title: 'Truman Kautzman'
theme: 'tilatrivia'

params:
  description: "Software Engineer and Designer"
  social:
    email: 'tilatrivia@gmail.com'
    github: 'tilatrivia'

menu:
  main:
    - identifier: "about"
      name: "About"
      url: "/about"
      weight: 10
      params:
        description: "My qualifications, skills, education, and experience"
    - identifier: "projects"
      name: "Projects"
      url: "/projects"
      weight: 20
      params:
        description: "Learn about and use personal projects of mine"
    - identifier: "inspiration"
      name: "Inspiration"
      url: "/inspiration"
      weight: 30
      params:
        description: "A collection of things that inspire me"

